### ISSUE TITLE
MVP User interface

### ISSUE THREAD

**Issue by filesync-online** [filesync-online/filesync#2]
Before I do any design work, I wanted to basically do a quick wireframe with elements that are needed. From what I can see the MVP just needs the following:
- Header with filesync name, logo, username, logout button
- Translation selection
- File selection/drop
- Output selector
- Translate button

See below:
![image](https://user-images.githubusercontent.com/50658466/57890619-8c5e4200-7838-11e9-940b-a347fb9c3fc2.png)

@pere5 What are your thoughts? Let me know, then I will move onto the actual design...

**Comment by pere5** [comment]
@filesync-online Du behöver inte göra en design. Funkionalitet som ovan räcker. Jag börjar med samma design som på http://karinforlag.se/

**Comment by filesync-online** [comment]
Closing this as we can now refer to issue #4
