### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by pere5** [filesync-online/filesync#4]
Utgå från layouten i http://karinforlag.se/ för alla sidor

**Comment by filesync-online** [comment]
Here is the layout based on Karin Förlag.

![Filesync](https://user-images.githubusercontent.com/50658466/57971030-fd147400-7988-11e9-9903-f8c9bf97a4bc.jpg)

Blue Color (Header & Text): Hex 005ead
Main Background Grey: Hex f5f5f5
Footer Dark Grey: Hex 777777
