### ISSUE TITLE
Updated Translation

### ISSUE THREAD

**Issue by filesync-online** [filesync-online/filesync#9]
Original: [DAG_2019-05-21-214104-start_stop_circulation_report.xlsx](https://github.com/filesync-online/filesync/files/3217412/DAG_2019-05-21-214104-start_stop_circulation_report.xlsx)
New:  [NEW_Start.Stop-2019-05-22.xlsx](https://github.com/filesync-online/filesync/files/3217413/NEW_Start.Stop-2019-05-22.xlsx)

**Comment by pere5** [comment]
@filesync-online C&C

**Comment by filesync-online** [comment]
@pere5 The site is down so I cannot test... but I have created a sheet that is correct that I can check it against. :)

**Comment by pere5** [comment]
@filesync-online Numbers match up exactly. Need to setup uptime robot to 104.248.130.169
https://github.com/filesync-online/filesync/issues/10
